- Proxmox Nodes:
  - Gate:
      href: https://gate.meext.net
      icon: proxmox.png
      description: Network Node
      ping: 199.198.0.10
      widget:
        type: proxmox
        url: https://gate.meext.net
        username: homepage@pam!homepage-integration
        password: 11d06b74-ac23-4b88-b17d-284fc4b2a39e
        node: core
  - Core:
      href: https://core.meext.net
      icon: proxmox.png
      description: Heavy Lift Node
      ping: 199.198.0.15
      widget:
        type: proxmox
        url: https://core.meext.net
        username: homepage@pam!homepage-integration
        password: 50c89cbf-31b2-4b52-b9c2-d356b343a85f
        node: core

- Network:
  - pfSense:
      href: https://pfsense.meext.net
      icon: pfsense.png
      description: Router
      ping: 199.198.0.1
  - adguard:
      href: https://adguard.meext.net
      icon: adguard-home.png
      description: DNS Controller
      ping: 199.198.0.2
      widget:
        type: adguard
        url: http://199.198.0.2
        username: root
        password: //Block13!
  - npm:
      href: https://proxy.meext.net
      icon: nginx-proxy-manager.png
      description: Proxy
      ping: 199.198.0.3
      widget:
        type: npm
        url: https://proxy.meext.net
        username: eu@gabrielpires.com.br
        password: dAxVLsA4YdJVbhX